"""Attack-Ray Sparse Attention (p007) — ray-cast sparse attention head.

Promoted from ``ideas/research/primitives/external_03_attack_ray_sparse_attention_delta_accumulator.md``
(top-ranked proposal: ARSA). The ARSA primitive is sparse attention whose
key set per query is generated by ray-casting through the input occupancy
bitmap, so the adjacency tensor is integer-valued and recomputed every
forward pass.

For each of 64 source squares we pick up to ``2 * NUM_DIRECTIONS = 16``
sparse keys: the first-blocker square on each of the 8 sliding rays, and
the source square itself (a self-edge keeping the soft-attention denominator
well-conditioned). The selected key set therefore has fixed cardinality
``K = 9`` per query (8 ray neighbours + self), avoiding ragged-tensor /
variable-shape kernels while still encoding the chess line-of-sight
inductive bias spelled out in the ARSA spec.

Architecture (additive, gated):

    base_logit       = i193_trunk(board)["logits"]
    sq_tokens        = SquareTokenEmbedder(board)            # (B, 64, d)
    blocker_idx      = first_blocker_indices(board)          # (B, 64, 8) long
    has_blocker      = has_blocker_mask                       # (B, 64, 8) bool
    K                = 8 ray neighbours + 1 self-edge
    attended         = sparse_softmax_attention(sq_tokens, blocker_idx, ...)
    pooled           = global_pool(attended)                 # (B, d)
    delta            = MLP(pooled)
    gate             = sigmoid(MLP(trunk_pool))
    final_logit      = base_logit + gate * delta

Deferred internal proposals from external_03 (DAP, Tree-S6, WrEC, SHK) are
documented in ``ablations.md``; they are not implemented in this head.
"""

from __future__ import annotations

import math
from typing import Any

import torch
import torch.nn.functional as F
from torch import nn

from chess_nn_playground.models.primitives.rule_graph_features import (
    NUM_DIRECTIONS,
    SQUARES,
    SquareTokenEmbedder,
    first_blocker_indices,
    rule_geometry,
)
from chess_nn_playground.models.trunk.exchange_then_king_dual_stream import (
    DualStreamFeatureBuilder,
    ExchangeThenKingDualStreamNetwork,
)
from chess_nn_playground.models.trunk.idea_blocks import BoardTensorSpec, require_board_tensor


ALLOWED_ABLATIONS: tuple[str, ...] = (
    "none",
    "uniform_attention",  # disable softmax weighting (fixed 1/K)
    "random_keys",        # replace ray neighbours with random other squares
    "no_blocker_mask",    # treat ray-end (off-board) as if it had a blocker (self)
    "zero_delta",
    "disable_gate",
    "trunk_only",
)


class AttackRaySparseAttention(nn.Module):
    """p007 — Attack-Ray Sparse Attention head over the i193 trunk."""

    def __init__(
        self,
        input_channels: int = 18,
        num_classes: int = 1,
        trunk_channels: int = 64,
        trunk_hidden_dim: int = 96,
        trunk_depth: int = 2,
        trunk_dropout: float = 0.1,
        trunk_use_batchnorm: bool = True,
        trunk_gate_dim: int | None = None,
        trunk_ablation: str = "none",
        token_embed_dim: int = 32,
        token_hidden_dim: int = 0,
        attn_dim: int = 32,
        head_hidden_dim: int = 64,
        head_dropout: float = 0.1,
        gate_init: float = -2.0,
        ablation: str = "none",
    ) -> None:
        super().__init__()
        if int(num_classes) != 1:
            raise ValueError(
                "AttackRaySparseAttention supports the puzzle_binary one-logit contract"
            )
        if int(input_channels) != 18:
            raise ValueError(
                "AttackRaySparseAttention requires the simple_18 board tensor"
            )
        if str(ablation) not in ALLOWED_ABLATIONS:
            raise ValueError(
                f"Unknown ablation={ablation!r}; expected one of {sorted(ALLOWED_ABLATIONS)}"
            )

        self.num_classes = 1
        self.ablation = str(ablation)
        self.spec = BoardTensorSpec(input_channels=int(input_channels))
        self._geometry = rule_geometry()
        # 8 ray neighbour slots + 1 self-edge.
        self._num_slots = NUM_DIRECTIONS + 1

        self.trunk = ExchangeThenKingDualStreamNetwork(
            input_channels=int(input_channels),
            num_classes=1,
            channels=int(trunk_channels),
            hidden_dim=int(trunk_hidden_dim),
            depth=int(trunk_depth),
            dropout=float(trunk_dropout),
            use_batchnorm=bool(trunk_use_batchnorm),
            gate_dim=trunk_gate_dim,
            ablation=str(trunk_ablation),
        )

        self.token_embed = SquareTokenEmbedder(
            input_channels=int(input_channels),
            embed_dim=int(token_embed_dim),
            hidden_dim=int(token_hidden_dim),
            dropout=float(head_dropout),
        )

        self.q_proj = nn.Linear(int(token_embed_dim), int(attn_dim))
        self.k_proj = nn.Linear(int(token_embed_dim), int(attn_dim))
        self.v_proj = nn.Linear(int(token_embed_dim), int(token_embed_dim))

        # Per-slot learned bias allowing the model to distinguish direction-of-ray
        # without leaking direction into the attention values themselves.
        self.slot_bias = nn.Parameter(torch.zeros(self._num_slots))

        trunk_pool_dim = (
            2 * self.trunk.exchange_encoder.output_dim
            + DualStreamFeatureBuilder.SUMMARY_DIM
        )
        self._trunk_pool_dim = trunk_pool_dim

        head_dropout_module: nn.Module = (
            nn.Dropout(float(head_dropout)) if float(head_dropout) > 0 else nn.Identity()
        )
        self.delta_head = nn.Sequential(
            nn.LayerNorm(int(token_embed_dim)),
            nn.Linear(int(token_embed_dim), int(head_hidden_dim)),
            nn.GELU(),
            head_dropout_module,
            nn.Linear(int(head_hidden_dim), 1),
        )
        self.gate_head = nn.Sequential(
            nn.LayerNorm(trunk_pool_dim),
            nn.Linear(trunk_pool_dim, int(head_hidden_dim)),
            nn.GELU(),
            nn.Linear(int(head_hidden_dim), 1),
        )
        with torch.no_grad():
            final_layer = self.gate_head[-1]
            if isinstance(final_layer, nn.Linear):
                final_layer.bias.fill_(float(gate_init))

    def _trunk_joint(self, board: torch.Tensor) -> tuple[dict[str, torch.Tensor], torch.Tensor]:
        trunk_out = self.trunk(board)
        feats = self.trunk.feature_builder(board)
        if self.trunk.ablation == "shared_stream_only":
            ex_input = board
            kg_input = board
        else:
            ex_input = torch.cat([board, feats.exchange], dim=1)
            kg_input = torch.cat([board, feats.king], dim=1)
        _, ex_pool = self.trunk.exchange_encoder(ex_input)
        if self.trunk.ablation == "shared_stream_only":
            kg_pool = ex_pool
        else:
            _, kg_pool = self.trunk.king_encoder(kg_input)
        joint = torch.cat([ex_pool, kg_pool, feats.summary], dim=1)
        return trunk_out, joint

    @torch.no_grad()
    def _build_key_indices(self, board: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Return ``(key_idx, key_valid)`` with shape ``(B, 64, num_slots)``.

        Slot 0..7 = first-blocker target per ray direction; slot 8 = source
        (self-edge). When a ray has no blocker the slot points at the
        source square and is marked invalid so the softmax ignores it
        unless the ablation says otherwise.
        """
        batch = board.shape[0]
        device = board.device
        target, has_blocker = first_blocker_indices(board, self._geometry)
        # (B, 64, 8) long and bool
        self_idx = torch.arange(SQUARES, device=device).view(1, SQUARES, 1).expand(batch, SQUARES, 1)
        key_idx = torch.cat([target, self_idx], dim=-1)  # (B, 64, 9)
        self_valid = torch.ones_like(has_blocker[:, :, :1])
        key_valid = torch.cat([has_blocker, self_valid], dim=-1)

        if self.ablation == "random_keys":
            rand = torch.randint(0, SQUARES, target.shape, device=device)
            key_idx = torch.cat([rand, self_idx], dim=-1)
            key_valid = torch.cat([torch.ones_like(rand, dtype=torch.bool), self_valid], dim=-1)
        if self.ablation == "no_blocker_mask":
            # Treat every slot as valid (off-board slots already point at self).
            key_valid = torch.ones_like(key_valid)
        return key_idx, key_valid

    def forward(self, x: torch.Tensor) -> dict[str, torch.Tensor]:
        board = require_board_tensor(x, self.spec)
        batch = board.shape[0]
        trunk_out, trunk_joint = self._trunk_joint(board)
        base_logit = trunk_out["logits"]

        tokens = self.token_embed(board)  # (B, 64, d)
        d = tokens.shape[-1]
        slot_count = self._num_slots

        key_idx, key_valid = self._build_key_indices(board)  # (B, 64, slots)
        valid_f = key_valid.to(dtype=tokens.dtype)
        gather_idx = key_idx.unsqueeze(-1).expand(batch, SQUARES, slot_count, d)
        token_keys = tokens.unsqueeze(1).expand(batch, SQUARES, SQUARES, d).gather(
            2, gather_idx
        )  # (B, 64, slots, d)

        q = self.q_proj(tokens)  # (B, 64, attn_dim)
        k = self.k_proj(token_keys)  # (B, 64, slots, attn_dim)
        v = self.v_proj(token_keys)  # (B, 64, slots, d)

        attn_logits = (q.unsqueeze(2) * k).sum(dim=-1) / math.sqrt(k.shape[-1])
        attn_logits = attn_logits + self.slot_bias.view(1, 1, slot_count)
        attn_logits = attn_logits.masked_fill(~key_valid, float("-inf"))

        if self.ablation == "uniform_attention":
            # Average over valid slots only.
            attn_weights = valid_f / valid_f.sum(dim=-1, keepdim=True).clamp_min(1.0)
        else:
            attn_weights = torch.softmax(attn_logits, dim=-1)
            # In the (very rare) edge case all slots invalid, attn_weights NaNs.
            attn_weights = torch.where(
                key_valid.any(dim=-1, keepdim=True),
                attn_weights,
                torch.zeros_like(attn_weights),
            )

        attended = (attn_weights.unsqueeze(-1) * v).sum(dim=2)  # (B, 64, d)
        attn_entropy = -(
            attn_weights.clamp_min(1.0e-8).log() * attn_weights
        ).sum(dim=-1)  # (B, 64)
        pooled = attended.mean(dim=1)  # (B, d)
        delta_raw = self.delta_head(pooled).view(-1)

        gate_logit = self.gate_head(trunk_joint.detach()).view(-1)
        gate = torch.sigmoid(gate_logit)
        if self.ablation == "disable_gate":
            gate = torch.ones_like(gate)
        if self.ablation in {"zero_delta", "trunk_only"}:
            primitive_delta = torch.zeros_like(base_logit)
        else:
            primitive_delta = gate * delta_raw
        if self.ablation == "trunk_only":
            primitive_delta = torch.zeros_like(primitive_delta)
        logits = base_logit + primitive_delta

        out: dict[str, torch.Tensor] = dict(trunk_out)
        out["logits"] = logits
        out["base_logit"] = base_logit
        out["primitive_delta"] = primitive_delta
        out["primitive_delta_raw"] = delta_raw
        out["primitive_gate"] = gate
        out["primitive_gate_logit"] = gate_logit
        out["arsa_blocker_count"] = key_valid[:, :, :NUM_DIRECTIONS].to(dtype=tokens.dtype).sum(dim=(1, 2))
        out["arsa_attention_entropy"] = attn_entropy.mean(dim=1)
        out["arsa_self_weight"] = attn_weights[..., NUM_DIRECTIONS].mean(dim=1)
        return out


def build_attack_ray_sparse_attention_from_config(
    config: dict[str, Any],
) -> AttackRaySparseAttention:
    cfg = dict(config)
    return AttackRaySparseAttention(
        input_channels=int(cfg.get("input_channels", 18)),
        num_classes=int(cfg.get("num_classes", 1)),
        trunk_channels=int(cfg.get("trunk_channels", cfg.get("channels", 64))),
        trunk_hidden_dim=int(cfg.get("trunk_hidden_dim", cfg.get("hidden_dim", 96))),
        trunk_depth=int(cfg.get("trunk_depth", cfg.get("depth", 2))),
        trunk_dropout=float(cfg.get("trunk_dropout", cfg.get("dropout", 0.1))),
        trunk_use_batchnorm=bool(cfg.get("trunk_use_batchnorm", cfg.get("use_batchnorm", True))),
        trunk_gate_dim=cfg.get("trunk_gate_dim", cfg.get("gate_dim", None)),
        trunk_ablation=str(cfg.get("trunk_ablation", "none")),
        token_embed_dim=int(cfg.get("token_embed_dim", 32)),
        token_hidden_dim=int(cfg.get("token_hidden_dim", 0)),
        attn_dim=int(cfg.get("attn_dim", 32)),
        head_hidden_dim=int(cfg.get("head_hidden_dim", 64)),
        head_dropout=float(cfg.get("head_dropout", 0.1)),
        gate_init=float(cfg.get("gate_init", -2.0)),
        ablation=str(cfg.get("ablation", "none")),
    )


_ = F  # quiet "F is unused" if it isn't needed by the runtime path
