"""Attack-Ray Sparse Attention spatial mixer (primitive p007).

The p007 ``AttackRaySparseAttention`` primitive is sparse attention whose
per-query key set is generated by ray-casting through the board occupancy:
for each of 64 source squares, the keys are the *first blocker* on each of
the 8 sliding rays (N, NE, E, SE, S, SW, W, NW) plus a self-edge, a fixed
cardinality of ``K = 9``. The dense 64x64 score matrix is never
instantiated; the key index tensor is a deterministic discrete function of
occupancy with ``stop_gradient``. Output is a softmax attention over the 9
gathered keys with a learned per-slot (per-direction) bias.

**Adaptation to the mixer contract.** The ray geometry -- the 8 directions,
the per-square ray-step target squares, on-board validity -- is pure 8x8
board geometry and is *channel-agnostic*; it is precomputed here exactly as
in the primitive's ``rule_graph_features``. The only board-derived quantity
the primitive needs is the scalar occupancy mask, which a mixer cannot read
(``C`` is opaque). We derive a soft occupancy from channel content, then
*discretise and detach* it so the first-blocker key indices remain a
non-differentiable discrete branch -- preserving the spec's defining
property. The 9-slot gather, the q/k/v projections, the per-slot direction
bias, and the masked softmax are all preserved exactly.

Honest compromise: occupancy is content-derived (a thresholded learned
scalar per square) instead of read from piece planes. Everything else --
ray-cast first-blocker key selection, fixed 9-slot sparse attention,
stop-gradient indices -- is faithful.
"""

from __future__ import annotations

import math

import torch
from torch import nn

from chess_nn_playground.models.architecture.bt4_mixers._base import register_mixer

_SQUARES = 64
_NUM_DIRECTIONS = 8
_MAX_RAY_LEN = 7
# Direction order N, NE, E, SE, S, SW, W, NW -- matches rule_graph_features.
_DIR_VECTORS = (
    (-1, 0), (-1, 1), (0, 1), (1, 1),
    (1, 0), (1, -1), (0, -1), (-1, -1),
)


def _build_ray_tables() -> tuple[torch.Tensor, torch.Tensor]:
    """Per-square ray-step target squares and on-board validity.

    Returns ``ray_step_target (64, 8, 7)`` long and ``ray_step_valid
    (64, 8, 7)`` bool. Off-board steps point at square 0 and are invalid.
    """
    target = torch.zeros(_SQUARES, _NUM_DIRECTIONS, _MAX_RAY_LEN, dtype=torch.long)
    valid = torch.zeros(_SQUARES, _NUM_DIRECTIONS, _MAX_RAY_LEN, dtype=torch.bool)
    for sq in range(_SQUARES):
        sr, sf = sq // 8, sq % 8
        for d, (dr, df) in enumerate(_DIR_VECTORS):
            r, f, step = sr + dr, sf + df, 0
            while 0 <= r < 8 and 0 <= f < 8 and step < _MAX_RAY_LEN:
                target[sq, d, step] = r * 8 + f
                valid[sq, d, step] = True
                r += dr
                f += df
                step += 1
    return target, valid


class AttackRaySparseAttentionMixer(nn.Module):
    def __init__(self, channels: int, attn_dim: int = 32) -> None:
        super().__init__()
        self.channels = int(channels)
        self._num_slots = _NUM_DIRECTIONS + 1  # 8 ray neighbours + self-edge

        target, valid = _build_ray_tables()
        self.register_buffer("ray_step_target", target, persistent=False)
        self.register_buffer("ray_step_valid", valid, persistent=False)

        # Content-derived (detached) soft occupancy scorer.
        self.occ_score = nn.Linear(self.channels, 1)

        ad = int(attn_dim)
        self.q_proj = nn.Linear(self.channels, ad)
        self.k_proj = nn.Linear(self.channels, ad)
        self.v_proj = nn.Linear(self.channels, self.channels)
        # Per-slot learned bias -> distinguishes ray direction without
        # leaking direction into the value tokens.
        self.slot_bias = nn.Parameter(torch.zeros(self._num_slots))
        self.norm = nn.LayerNorm(self.channels)

    @torch.no_grad()
    def _build_key_indices(self, tokens: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """First-blocker key indices ``(B, 64, 9)`` + validity, fully detached."""
        b = tokens.shape[0]
        device = tokens.device
        # Soft occupancy -> hard 0/1, detached: a non-differentiable branch.
        occ = (self.occ_score(tokens).squeeze(-1) > 0.0)  # (B, 64) bool

        ray_target = self.ray_step_target.to(device)  # (64, 8, 7)
        ray_valid = self.ray_step_valid.to(device)
        ray_count = ray_valid.sum(dim=-1)  # (64, 8)

        flat_target = ray_target.reshape(-1)
        occ_along = occ.index_select(1, flat_target).view(
            b, _SQUARES, _NUM_DIRECTIONS, _MAX_RAY_LEN
        )
        occ_bool = occ_along & ray_valid.unsqueeze(0)

        step_idx = torch.arange(_MAX_RAY_LEN, device=device).view(1, 1, 1, -1)
        masked_step = torch.where(
            occ_bool,
            step_idx.expand_as(occ_bool),
            torch.full_like(occ_bool, _MAX_RAY_LEN, dtype=torch.long),
        )
        first_step = masked_step.min(dim=-1).values  # (B, 64, 8)
        has_blocker = first_step < ray_count.unsqueeze(0).expand_as(first_step)

        clamped = first_step.clamp(0, _MAX_RAY_LEN - 1)
        target = ray_target.unsqueeze(0).expand(b, -1, -1, -1).gather(
            -1, clamped.unsqueeze(-1)
        ).squeeze(-1)  # (B, 64, 8)
        self_idx = torch.arange(_SQUARES, device=device).view(1, _SQUARES, 1)
        target = torch.where(has_blocker, target, self_idx.expand_as(target))

        self_col = self_idx.expand(b, _SQUARES, 1)
        key_idx = torch.cat([target, self_col], dim=-1)  # (B, 64, 9)
        key_valid = torch.cat(
            [has_blocker, torch.ones_like(self_col, dtype=torch.bool)], dim=-1
        )
        return key_idx, key_valid

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        b, c, h, w = x.shape
        tokens = x.flatten(2).transpose(1, 2)  # (B, 64, C)
        n = tokens.shape[1]
        slots = self._num_slots

        key_idx, key_valid = self._build_key_indices(tokens)  # stop-grad

        gather_idx = key_idx.unsqueeze(-1).expand(b, n, slots, c)
        token_keys = tokens.unsqueeze(1).expand(b, n, n, c).gather(2, gather_idx)
        # (B, 64, 9, C)

        q = self.q_proj(tokens)  # (B, 64, attn_dim)
        k = self.k_proj(token_keys)  # (B, 64, 9, attn_dim)
        v = self.v_proj(token_keys)  # (B, 64, 9, C)

        attn_logits = (q.unsqueeze(2) * k).sum(dim=-1) / math.sqrt(k.shape[-1])
        attn_logits = attn_logits + self.slot_bias.view(1, 1, slots)
        attn_logits = attn_logits.masked_fill(~key_valid, float("-inf"))
        attn_weights = torch.softmax(attn_logits, dim=-1)
        # Guard the (rare) all-invalid row -- self-edge is always valid so
        # this is belt-and-braces.
        attn_weights = torch.where(
            key_valid.any(dim=-1, keepdim=True),
            attn_weights,
            torch.zeros_like(attn_weights),
        )

        attended = (attn_weights.unsqueeze(-1) * v).sum(dim=2)  # (B, 64, C)
        attended = self.norm(attended)
        return attended.transpose(1, 2).reshape(b, c, h, w)


@register_mixer("attack_ray_sparse_attention")
def build(channels: int, attn_dim: int = 32, **_: object) -> nn.Module:
    return AttackRaySparseAttentionMixer(channels=channels, attn_dim=attn_dim)
