"""Scaffold one trainable idea folder per bt4_primitive_mixer mixer.

For every chess-research primitive that has a working bt4 mixer (a file under
``src/chess_nn_playground/models/architecture/bt4_mixers/`` registering a mixer
with that primitive's slug), this generates an ``a###_bt4_<slug>_mixer`` idea
folder: a BT4-style residual tower whose per-block spatial mixer is that
primitive.

Each primitive is GATED first: the script builds the full ``bt4_primitive_mixer``
model with that mixer and runs a forward + backward pass. Only primitives that
pass the gate get an idea folder. The model alias ``bt4_<slug>_mixer`` is
auto-registered by registry.py, so each idea's ``config.yaml model.name``
matches its slug, which the idea scaffold validator requires.

Run:
    PYTHONDONTWRITEBYTECODE=1 python scripts/ideas/scaffold_bt4_primitive_mixers.py
    PYTHONDONTWRITEBYTECODE=1 python scripts/ideas/scaffold_bt4_primitive_mixers.py --overwrite
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _bootstrap import bootstrap  # noqa: E402

bootstrap()

import torch  # noqa: E402

from chess_nn_playground.ideas.implementation import validate_idea_for_training  # noqa: E402
from chess_nn_playground.models.architecture.bt4_mixers import available_mixers  # noqa: E402
from chess_nn_playground.models.registry import build_model  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_DIR = REPO_ROOT / "ideas" / "registry"
BASELINE_MIXERS = {"conv", "attention"}  # not chess-research primitives, skipped


def primitive_folders() -> list[Path]:
    folders = sorted(
        [
            p
            for p in REGISTRY_DIR.glob("p[0-9][0-9][0-9]_*")
            if p.is_dir()
        ]
        + [
            p
            for p in REGISTRY_DIR.glob("i24[4-8]_*")
            if p.is_dir()
        ]
    )
    return folders


def slug_of(folder: Path) -> str:
    # strip the "pNNN_" / "iNNN_" prefix
    return folder.name.split("_", 1)[1]


def gate_mixer(mixer: str) -> tuple[bool, str]:
    """Build the full bt4_primitive_mixer with this mixer; forward + backward."""
    try:
        model = build_model(
            "bt4_primitive_mixer",
            {"input_channels": 18, "num_classes": 1, "channels": 64, "num_blocks": 4, "mixer": mixer},
        )
        x = torch.randn(2, 18, 8, 8)
        out = model(x)["logits"]
        if out.shape != (2,) or not torch.isfinite(out).all():
            return False, f"bad forward output shape/finite: {tuple(out.shape)}"
        out.sum().backward()
        return True, "ok"
    except Exception as exc:  # noqa: BLE001
        return False, f"{type(exc).__name__}: {exc}"


def idea_yaml(idea_id: str, slug: str, primitive_folder: str) -> str:
    return f"""idea_id: {idea_id}
name: BT4 Primitive Mixer ({slug})
slug: bt4_{slug}_mixer
status: implemented
created_at: '2026-05-14T10:00:00+00:00'
author: Claude
short_thesis: >-
  BT4-style residual tower whose per-block spatial-mixing operator is the
  {slug} primitive instead of the original conv pair. Tests whether this
  chess-aware primitive is a better spatial mixer than conv or attention
  inside a fixed BT4 tower shell.
novelty_claim: >-
  Not a new primitive. A controlled architecture study: the bt4_primitive_mixer
  tower (stem, N residual+SE blocks, value head) is held fixed and only the
  per-block spatial mixer is swapped to the {slug} primitive, adapted to the
  (B, C, 8, 8) -> (B, C, 8, 8) mixer contract.
expected_advantage: >-
  Isolates the {slug} primitive's value as a token mixer against the conv and
  attention baselines under one identical tower, optimizer, and data contract.
target_task: >-
  puzzle_binary classification. Fine labels 0 and 1 map to non-puzzle, fine
  label 2 maps to puzzle.
input_representation: >-
  Current-board simple_18 tensor only. CRTK and source metadata are
  reporting-only and never used as model input.
output_heads: One puzzle logit for the puzzle_binary BCE-with-logits trainer.
compute_notes: >-
  Shared bt4_primitive_mixer net (registered alias bt4_{slug}_mixer). The
  mixer module lives at
  src/chess_nn_playground/models/architecture/bt4_mixers/{slug}.py and obeys
  the shape-preserving spatial-mixer contract; the BT4 block wraps it with
  SqueezeExcite plus residual.
implementation_status: implemented
trainer_entrypoint: ideas/registry/{idea_id}_bt4_{slug}_mixer/train.py
config_path: ideas/registry/{idea_id}_bt4_{slug}_mixer/config.yaml
model_path: ideas/registry/{idea_id}_bt4_{slug}_mixer/model.py
latest_result_path: null
notes: >-
  Generated by scripts/ideas/scaffold_bt4_primitive_mixers.py. Source primitive
  idea: {primitive_folder}. The mixer was gated with a build plus forward plus
  backward smoke test before this folder was created.
implementation_kind: bespoke_model
"""


def config_yaml(idea_id: str, slug: str) -> str:
    return f"""idea_id: {idea_id}
run:
  name: {idea_id}_bt4_{slug}_mixer_simple18
  output_dir: results
seed: 42
deterministic: true
mode: puzzle_binary
device: nvidia
data:
  train_path: data/splits/crtk_sample_3class_unique_crtk_tags/split_train.parquet
  val_path: data/splits/crtk_sample_3class_unique_crtk_tags/split_val.parquet
  test_path: data/splits/crtk_sample_3class_unique_crtk_tags/split_test.parquet
  encoding: simple_18
  cache_features: false
model:
  name: bt4_{slug}_mixer
  mixer: {slug}
  input_channels: 18
  num_classes: 1
  channels: 64
  num_blocks: 4
  value_channels: 16
  value_hidden: 128
  se_channels: 16
  dropout: 0.1
  use_batchnorm: true
  mechanism_family: bt4_mixer
  packet_profile: bt4_{slug}_mixer
training:
  epochs: 20
  batch_size: 256
  num_workers: auto
  persistent_workers: true
  prefetch_factor: 2
  learning_rate: 0.0007
  weight_decay: 0.0001
  class_weighting: balanced
  loss: bce_with_logits
  early_stopping_patience: 5
  mixed_precision: true
  allow_tf32: true
  matmul_precision: high
  reliability_tier: paper_grade
  min_epochs: 10
  min_active_epochs: 10
  gradient_clip_norm: 1.0
  lr_scheduler:
    name: reduce_on_plateau
    factor: 0.5
    patience: 2
    min_lr: 1.0e-05
notes: BT4-style tower with the {slug} primitive as the per-block spatial mixer.
  CRTK metadata is reporting-only.
"""


def model_py(slug: str) -> str:
    return f'''from __future__ import annotations

from typing import Any

from chess_nn_playground.models.architecture.bt4_primitive_mixer import (
    BT4PrimitiveMixerNet,
    build_bt4_primitive_mixer_from_config,
)


def build_model_from_config(config: dict[str, Any]) -> BT4PrimitiveMixerNet:
    model_cfg = dict(config.get("model", {{}}))
    model_cfg.setdefault("mixer", "{slug}")
    model_cfg.setdefault("num_classes", 1)
    return build_bt4_primitive_mixer_from_config(model_cfg)
'''


TRAIN_PY = """from __future__ import annotations

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "src"
for path in (SRC_ROOT, PROJECT_ROOT):
    path_text = str(path)
    if path_text not in sys.path:
        sys.path.insert(0, path_text)

from chess_nn_playground.ideas.implementation import idea_train_cli


if __name__ == "__main__":
    idea_train_cli(__file__)
"""


def architecture_md(slug: str, primitive_folder: str) -> str:
    return f"""# Architecture

`BT4 Primitive Mixer ({slug})` is a controlled architecture study, not a new
primitive. It holds the BT4-style residual tower fixed and swaps only the
per-block spatial-mixing operator.

## Implementation Binding

- Registered model name: `bt4_{slug}_mixer` (alias of `bt4_primitive_mixer`
  with `mixer={slug}`)
- Tower: `src/chess_nn_playground/models/architecture/bt4_primitive_mixer.py`
- Mixer: `src/chess_nn_playground/models/architecture/bt4_mixers/{slug}.py`
- Source primitive idea: `{primitive_folder}`

## What this is

The `bt4_primitive_mixer` tower mirrors `lc0_bt4_classifier`: a stem conv, N
residual blocks each `mixer -> SqueezeExcite -> +residual -> ReLU`, then the
value head. The original lc0_bt4 block mixes spatially with a pair of 3x3
convs. Here that mixer is replaced by the `{slug}` primitive, adapted to the
shape-preserving `(B, C, 8, 8) -> (B, C, 8, 8)` mixer contract.

Because the tower, optimizer protocol, data contract, and training
hyperparameters are identical across every `a###_bt4_*_mixer` idea and the
`conv` / `attention` baselines, the only variable is the mixer. That makes
this the cleanest available test of "is the `{slug}` primitive a better
spatial mixer than conv or attention?".

## Contract

- Input: `(B, 18, 8, 8)` simple_18 board tensor only.
- Output: `dict` with `logits` of shape `(B,)` for the one-logit puzzle_binary
  BCE-with-logits trainer.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--overwrite", action="store_true", help="recreate folders that already exist")
    ap.add_argument("--manifest", type=Path, default=REPO_ROOT / "reports" / "bt4_primitive_mixers" / "manifest.txt")
    args = ap.parse_args()

    registered = set(available_mixers())
    folders = primitive_folders()
    created: list[str] = []
    gated_out: list[tuple[str, str]] = []
    validation_failed: list[tuple[str, list[str]]] = []
    skipped_existing: list[str] = []

    next_id = 1
    for folder in folders:
        slug = slug_of(folder)
        if slug not in registered:
            gated_out.append((slug, "no registered mixer"))
            continue
        ok, msg = gate_mixer(slug)
        if not ok:
            gated_out.append((slug, msg))
            continue

        idea_id = f"a{next_id:03d}"
        next_id += 1
        idea_folder = REGISTRY_DIR / f"{idea_id}_bt4_{slug}_mixer"

        if idea_folder.exists() and not args.overwrite:
            skipped_existing.append(idea_folder.name)
            continue

        (idea_folder / "runs").mkdir(parents=True, exist_ok=True)
        (idea_folder / "idea.yaml").write_text(idea_yaml(idea_id, slug, folder.name))
        (idea_folder / "config.yaml").write_text(config_yaml(idea_id, slug))
        (idea_folder / "model.py").write_text(model_py(slug))
        (idea_folder / "train.py").write_text(TRAIN_PY)
        (idea_folder / "architecture.md").write_text(architecture_md(slug, folder.name))

        result = validate_idea_for_training(idea_folder)
        if not result["valid"]:
            validation_failed.append((idea_folder.name, result["issues"]))
        else:
            created.append(idea_folder.name)

    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text("\n".join(sorted(created)) + ("\n" if created else ""))

    print(f"Created + validated: {len(created)}")
    for name in sorted(created):
        print(f"  OK   {name}")
    if skipped_existing:
        print(f"Skipped (already exist, use --overwrite): {len(skipped_existing)}")
        for name in skipped_existing:
            print(f"  SKIP {name}")
    if gated_out:
        print(f"Gated out (mixer build/forward failed): {len(gated_out)}")
        for slug, why in gated_out:
            print(f"  GATE {slug}: {why}")
    if validation_failed:
        print(f"Validation failed: {len(validation_failed)}")
        for name, issues in validation_failed:
            print(f"  FAIL {name}")
            for issue in issues:
                print(f"        {issue}")
    print(f"\nManifest of trainable ideas: {args.manifest}")


if __name__ == "__main__":
    main()
