#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

import sys



from chess_nn_playground.ideas.registry import validate_ideas
from chess_nn_playground.utils.config import save_yaml


SYNTHETIC_ROWS = [
    {
        "fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "label_status": "known_non_puzzle",
        "source_group_id": "synthetic_ordinary_1",
    },
    {
        "fen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2",
        "label_status": "known_non_puzzle",
        "source_group_id": "synthetic_ordinary_2",
    },
    {
        "fen": "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
        "label_status": "candidate_1_or_2_unresolved",
        "sister_group_id": "synthetic_candidate_a",
    },
    {
        "fen": "r2qkbnr/ppp2ppp/2np4/4p3/2B1P1b1/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 5",
        "label_status": "candidate_1_or_2_unresolved",
        "sister_group_id": "synthetic_candidate_b",
    },
    {
        "fen": "rnbq1bnr/ppppkppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQ - 2 3",
        "label_status": "known_non_puzzle",
        "source_group_id": "synthetic_ordinary_3",
    },
    {
        "fen": "rnbqkbnr/ppp2ppp/3p4/4p3/4P3/2N5/PPPP1PPP/R1BQKBNR w KQkq - 0 3",
        "label_status": "candidate_1_or_2_unresolved",
        "sister_group_id": "synthetic_candidate_c",
    },
]


def run(command: list[str]) -> None:
    print("$ " + " ".join(command))
    subprocess.run(command, check=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run a small end-to-end smoke test on synthetic data.")
    parser.add_argument("--device", default="nvidia", help="Torch device for the tiny training run, e.g. nvidia or cpu")
    parser.add_argument("--output-dir", default="results/smoke", help="Output directory for the tiny training run")
    args = parser.parse_args()

    smoke_dir = Path("data/raw/smoke")
    if smoke_dir.exists():
        shutil.rmtree(smoke_dir)
    smoke_dir.mkdir(parents=True, exist_ok=True)
    jsonl_path = smoke_dir / "synthetic_positions.jsonl"
    with jsonl_path.open("w", encoding="utf-8") as handle:
        for row in SYNTHETIC_ROWS:
            handle.write(json.dumps(row) + "\n")

    run([sys.executable, "-m", "scripts.data.inspect_json_data", "--input", str(jsonl_path), "--output-json", "data/reports/smoke_json_data_audit.json", "--output-md", "data/reports/smoke_json_data_audit.md"])
    run([sys.executable, "-m", "scripts.data.prepare_dataset", "--input", str(jsonl_path), "--output", "data/processed/smoke_positions.parquet", "--rejected-output", "data/processed/smoke_rejected_positions.parquet"])
    smoke_splits_dir = Path("data/splits/smoke")
    run([
        sys.executable,
        "-m",
        "scripts.data.generate_splits",
        "--input",
        "data/processed/smoke_positions.parquet",
        "--output-dir",
        str(smoke_splits_dir),
        "--mode",
        "coarse_binary",
        "--seed",
        "7",
        "--report-md",
        "data/reports/smoke_split_report.md",
    ])
    smoke_config_path = Path("data/reports/smoke_cnn_config.yaml")
    save_yaml(
        {
            "run": {"name": "smoke_cnn", "output_dir": args.output_dir},
            "seed": 7,
            "deterministic": True,
            "mode": "coarse_binary",
            "device": args.device,
            "data": {
                "train_path": str(smoke_splits_dir / "split_train.parquet"),
                "val_path": str(smoke_splits_dir / "split_val.parquet"),
                "test_path": str(smoke_splits_dir / "split_test.parquet"),
                "encoding": "simple_18",
                "cache_features": True,
            },
            "model": {
                "name": "simple_cnn",
                "input_channels": 18,
                "num_classes": 2,
                "channels": 4,
                "num_blocks": 1,
                "dropout": 0.0,
                "use_batchnorm": False,
            },
            "training": {
                "epochs": 1,
                "batch_size": 2,
                "num_workers": 0,
                "learning_rate": 0.001,
                "weight_decay": 0.0,
                "class_weighting": "none",
                "early_stopping_patience": 1,
                "mixed_precision": False,
            },
            "notes": "Synthetic smoke-test config generated by scripts/dev/smoke_test.py.",
        },
        smoke_config_path,
    )
    run([sys.executable, "-m", "scripts.dev.train_cnn", "--config", str(smoke_config_path)])
    run([sys.executable, "-m", "scripts.compare_results"])
    idea_report = validate_ideas()
    if not idea_report["valid"]:
        raise SystemExit(f"Idea registry validation failed: {idea_report}")
    print("Smoke test completed.")


if __name__ == "__main__":
    main()
